name: romrom_fe
description: "ROMROM-FE"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.9.6+149
environment:
  sdk: ">=3.9.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  # 알파벳 순으로 정렬
  animated_toggle_switch: ^0.8.5
  cupertino_icons: ^1.0.6
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter_dotenv: ^5.2.1
  flutter_lints: ^3.0.0
  flutter_local_notifications: ^19.5.0
  flutter_naver_map: ^1.3.1
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  google_sign_in: ^6.2.2
  gradient_borders: ^1.0.1
  http: ^1.3.0
  http_parser: ^4.0.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  kakao_flutter_sdk: ^1.9.7+3
  logging: ^1.3.0
  permission_handler: ^11.3.1
  photo_viewer: ^0.1.0
  playing_cards_layouts: ^1.0.1
  provider: ^6.1.5
  shadex: ^1.0.2
  shared_preferences: ^2.5.2
  skeletonizer: ^2.1.0+1
  stomp_dart_client: ^2.0.0
  cached_network_image: ^3.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  patrol: ^4.1.0
# Patrol 설정
patrol:
  app_name: 롬롬
  test_directory: integration_test
  android:
    package_name: com.alom.romrom
  ios:
    bundle_id: com.alom.romrom
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/terms/
  fonts:
    # icons
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
    # fonts
    - family: Pretendard
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/pretendard/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/pretendard/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/pretendard/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/pretendard/Pretendard-Black.otf
          weight: 900
    # fonts
    - family: NEXON-Lv2-Gothic
      fonts:
        - asset: assets/fonts/nexon-lev2-gothic/NEXON-Lv2-Gothic-Light.otf
          weight: 300
        - asset: assets/fonts/nexon-lev2-gothic/NEXON-Lv2-Gothic.otf
          weight: 400
        - asset: assets/fonts/nexon-lev2-gothic/NEXON-Lv2-Gothic-Medium.otf
          weight: 500
        - asset: assets/fonts/nexon-lev2-gothic/NEXON-Lv2-Gothic-Bold.otf
          weight: 700
